apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentiment-api-grafana
  name: sentiment-api-grafana
  namespace: development
spec:
  ports:
  - name: grafana-http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sentiment-api-grafana
  type: ClusterIP
status:
  loadBalancer: {}
